### ISSUE TITLE
TypeError: Cannot read property 'ClientPeoplePickerSearchUser' of undefined

### ISSUE THREAD

**Issue by GitRanjith** [itszerocode/react-sp-people-picker#1]
Hi 
People picker is not working properly it give error as  "TypeError: Cannot read property 'ClientPeoplePickerSearchUser' of undefined"  can you help on this?

my code is :...

import * as React from 'react';
import styles from './Dmdproject.module.scss';
import { IDmdprojectProps } from './IDmdprojectProps';
import { escape } from '@microsoft/sp-lodash-subset';
import FirstFile from './MyRasieRequest';
import MyFirstFile from './MyRasieRequest';
import MySecondFile from './MySecondFile';
import { peoplePicker } from 'office-ui-fabric-react/lib/components/FloatingPicker/PeoplePicker/PeoplePicker.scss';
import { PeoplePicker } from '@pnp/spfx-controls-react/lib/PeoplePicker';
import { sp } from "@pnp/sp";
import context from 'react-bootstrap/esm/AccordionContext';
import SpPeoplePicker from 'react-sp-people-picker'
import 'react-sp-people-picker/dist/index.css'
let glbcontext;

export default class Dmdproject extends React.Component<IDmdprojectProps, {}> {
  public render(): React.ReactElement<IDmdprojectProps> {

    const handleSelect=(user)=>{
      console.log(user)
      }

      return <SpPeoplePicker onSelect={handleSelect} />
 
   
    return (
      <div>
      

       
      <SpPeoplePicker onSelect={handleSelect}></SpPeoplePicker>
      </div>
    );

  }
}

**Comment by GitRanjith** [comment]
Getting below log in console 
TypeError: Cannot read property 'ClientPeoplePickerSearchUser' of undefined
    at dmdproject-web-part_110f473bd0ca5723d622d60ce38b5533.js:1

**Comment by GitRanjith** [comment]
![image](https://user-images.githubusercontent.com/33476272/97085454-40254d00-163b-11eb-9980-377fda9dd98e.png)

**Comment by itscodezero** [comment]
@GitRanjith  there are a couple of things you need to change in your code. 

remove the multiple imports for SpPeoplePicker. just keep
import SpPeoplePicker from 'react-sp-people-picker'
import 'react-sp-people-picker/dist/index.css' 

these two. 

secondly, you have two different return statements in your code you need to remove the first one. 
const handleSelect=(user)=>{
  console.log(user)
  }
  **return <   SpPeoplePicker onSelect={handleSelect}    />**  //remove this one. 
return (
  <div>
  <  SpPeoplePicker onSelect={handleSelect}   ><  /SpPeoplePicker >
  </div>
)
