### ISSUE TITLE
I can't set default Value

### ISSUE THREAD

**Issue by ghost** [itszerocode/react-sp-people-picker#2]
Hi
I can't  pass default Value as a parameter  in <SpPeoplePicker onSelect={handleSelect} />.
may you help me how can I set default value for this component in a React app?

**Comment by itscodezero** [comment]
Hi, 
Can you please share your sample code here.. so I will be clear what you are suggesting.

**Comment by ghost** [comment]
Hi,
Please add other event attribute like onChange, onBlur even or defaultValue in your package. onSelect attribute just worked on this package.
Thanks

**Comment by itscodezero** [comment]
OnSelect and OnChange would do the same thing. But if you have code for
defaultValue, please add it and raise pull request. :)

Thanks for using the plug-in and looking forward to the community to
improve it further
